let shopItemsData = [
   
  {
    id: "abcde",
    name: "Shirt",
    price: 82,
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing.",
    img: "Images/img-1.jpg",
  },
  {
    id: "fghij",
    name: "Formal Shirts",
    price: 33,
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing.",
    img: "Images/img-2.jpg",
  },
  {
    id: "klmno",
    name: "Office Shirt",
    price: 49,
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing.",
    img: "Images/img-3.jpg",
  },
  {
    id: "pqrst",
    name: "Blazer",
    price: 70,
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing.",
    img: "Images/img-4.jpg",
  },
  {
    id: "abcsdde",
    name: "Tie",
    price: 82,
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing.",
    img: "Images/img-5.png",
  },
  {
    id: "fgrhhij",
    name: "Shoes",
    price: 33,
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing.",
    img: "Images/img-6.png",
  },
  {
    id: "klmneweo",
    name: "Formal Blazer",
    price: 49,
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing.",
    img: "Images/img-7.png",
  },
  {
    id: "pqrsett",
    name: "T-shirt",
    price: 70,
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing.",
    img: "Images/img-8.png",
  },
  {
    id: "abcdmlke",
    name: "Denims",
    price: 82,
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing.",
    img: "Images/img-9.png",
  },
  {
    id: "fghipopj",
    name: "Jeans",
    price: 33,
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing.",
    img: "Images/img-10.png",
  },
  {
    id: "klmnaeeo",
    name: "Caps",
    price: 49,
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing.",
    img: "Images/img-11.png",
  },
  {
    id: "pqrpoepst",
    name: "Boots",
    price: 70,
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing.",
    img: "Images/img-12.png",
  },
  {
    id: "abckdvsefkde",
    name: "White Tee",
    price: 82,
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing.",
    img: "Images/img-13.jpg",
  },
  {
    id: "abcdasge",
    name: "Shirt",
    price: 82,
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing.",
    img: "Images/img-1.jpg",
  },
  {
    id: "fghifgwej",
    name: "Formal Shirts",
    price: 33,
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing.",
    img: "Images/img-2.jpg",
  },
  {
    id: "klmnofwe",
    name: "Office Shirt",
    price: 49,
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing.",
    img: "Images/img-3.jpg",
  },
  {
    id: "pqrstfwe",
    name: "Blazer",
    price: 70,
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing.",
    img: "Images/img-4.jpg",
  },
  {
    id: "abcsddefwe",
    name: "Tie",
    price: 82,
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing.",
    img: "Images/img-5.png",
  },
  {
    id: "fgrhhiawj",
    name: "Shoes",
    price: 33,
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing.",
    img: "Images/img-6.png",
  },
  {
    id: "klmnewpopeo",
    name: "Formal Blazer",
    price: 49,
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing.",
    img: "Images/img-7.png",
  },
  {
    id: "pqrseewtt",
    name: "T-shirt",
    price: 70,
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing.",
    img: "Images/img-8.png",
  },
  {
    id: "abcdmlvsdke",
    name: "Denims",
    price: 82,
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing.",
    img: "Images/img-9.png",
  },
  {
    id: "fghiposfpj",
    name: "Jeans",
    price: 33,
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing.",
    img: "Images/img-10.png",
  },
  {
    id: "klmnaeefweeo",
    name: "Caps",
    price: 49,
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing.",
    img: "Images/img-11.png",
  },
  {
    id: "pqrpoeafpst",
    name: "Boots",
    price: 70,
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing.",
    img: "Images/img-12.png",
  },
  
  ];